# Generated by Django 2.1.2 on 2019-01-07 13:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmericanQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField()),
                ('indexOfCorrectAnswer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='fake')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('description', models.TextField()),
                ('picturesURLS', django.contrib.postgres.fields.jsonb.JSONField()),
                ('videosURLS', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('questionNumber', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('questionNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.Feedback')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('questionNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.Feedback')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FindTheDifferences',
            fields=[
                ('entertainmentNumber', models.AutoField(primary_key=True, serialize=False)),
                ('pictureURL', models.TextField()),
                ('differences', django.contrib.postgres.fields.jsonb.JSONField()),
                ('myAttraction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Server.Attraction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('hintNumber', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('HT', 'HintText'), ('HP', 'HintPicture'), ('HV', 'HintVideo'), ('HM', 'HintMap')], default='HT', max_length=2)),
                ('data', models.TextField()),
                ('myAttraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.Attraction')),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('entertainmentNumber', models.AutoField(primary_key=True, serialize=False)),
                ('pictureURL', models.TextField()),
                ('myAttraction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Server.Attraction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlidingPuzzle',
            fields=[
                ('entertainmentNumber', models.AutoField(primary_key=True, serialize=False)),
                ('piecesURLS', django.contrib.postgres.fields.jsonb.JSONField()),
                ('myAttraction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Server.Attraction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('points', models.ManyToManyField(to='Server.Attraction')),
                ('subTrack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Server.Track')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.TextField(default='fake')),
                ('playersAges', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('score', models.IntegerField(default=0)),
                ('attractionsDone', models.ManyToManyField(to='Server.Attraction')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.Track')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('socialNetwork', models.TextField()),
                ('lastSeen', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name', 'socialNetwork')},
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.User'),
        ),
        migrations.AddField(
            model_name='feedbacktext',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.Trip'),
        ),
        migrations.AddField(
            model_name='feedbackrating',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.Trip'),
        ),
        migrations.AddField(
            model_name='americanquestion',
            name='myAttraction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Server.Attraction'),
        ),
        migrations.AlterUniqueTogether(
            name='slidingpuzzle',
            unique_together={('entertainmentNumber', 'myAttraction')},
        ),
        migrations.AlterUniqueTogether(
            name='puzzle',
            unique_together={('entertainmentNumber', 'myAttraction')},
        ),
        migrations.AlterUniqueTogether(
            name='hint',
            unique_together={('hintNumber', 'myAttraction')},
        ),
        migrations.AlterUniqueTogether(
            name='findthedifferences',
            unique_together={('entertainmentNumber', 'myAttraction')},
        ),
        migrations.AlterUniqueTogether(
            name='feedbacktext',
            unique_together={('questionNumber', 'trip')},
        ),
        migrations.AlterUniqueTogether(
            name='feedbackrating',
            unique_together={('questionNumber', 'trip')},
        ),
    ]
