# Generated by Django 2.1.2 on 2019-03-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='subTrack',
        ),
    ]
