# Generated by Django 2.1.2 on 2018-12-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastSeen',
            field=models.DateField(null=True),
        ),
    ]
