# Generated by Django 2.1.2 on 2018-12-21 06:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='playersAges',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
