# Generated by Django 2.1.2 on 2018-12-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_auto_20181221_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastSeen',
            field=models.DateField(blank=True, null=True),
        ),
    ]
