# Generated by Django 2.1.2 on 2018-12-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
            ],
        ),
    ]
