//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trumpeldor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("trumpeldor.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבלו רמז נוסף.
        /// </summary>
        public static string add_hint {
            get {
                return ResourceManager.GetString("add_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף שחקן.
        /// </summary>
        public static string add_player {
            get {
                return ResourceManager.GetString("add_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גיל.
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בכניסה ללא התחברות, לא ישמרו נתוני המשחק ביציאה מהאפליקציה. האם אתם בטוחים?.
        /// </summary>
        public static string anonymous_alert {
            get {
                return ResourceManager.GetString("anonymous_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תשובה.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעות
        ///יש להמתין.
        /// </summary>
        public static string aq_explanation {
            get {
                return ResourceManager.GetString("aq_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגעת.
        /// </summary>
        public static string arrived {
            get {
                return ResourceManager.GetString("arrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לקבלת הרמז הבא השלימו:.
        /// </summary>
        public static string AttractionPageTitle {
            get {
                return ResourceManager.GetString("AttractionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לחץ המשך כדי לראות את מיקום היעד במפה.
        /// </summary>
        public static string click_ok_to_view_the_next_point_on_the_map {
            get {
                return ResourceManager.GetString("click_ok_to_view_the_next_point_on_the_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סגור.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ברכות סיימת את המסלול עם .
        /// </summary>
        public static string congrdulation_you_finish_the_track_with {
            get {
                return ResourceManager.GetString("congrdulation_you_finish_the_track_with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האריכו את המסלול.
        /// </summary>
        public static string continue_to_longer_track {
            get {
                return ResourceManager.GetString("continue_to_longer_track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבלו את הרמז
        ///לנקודה הבאה.
        /// </summary>
        public static string continue_trip {
            get {
                return ResourceManager.GetString("continue_trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צרו את הקבוצה שלכם.
        /// </summary>
        public static string Create_your_group {
            get {
                return ResourceManager.GetString("Create_your_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיימת יעד!.
        /// </summary>
        public static string Destionation_Complete {
            get {
                return ResourceManager.GetString("Destionation_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רוצה להמשיך את המסלול הקודם שלך?.
        /// </summary>
        public static string Do_you_want_to_continue_last_trip {
            get {
                return ResourceManager.GetString("Do_you_want_to_continue_last_trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כל הכבוד סיימת את הטיול, נשמח למשוב עליו. האם ברצונך לעבור לדף המשוב?.
        /// </summary>
        public static string Done_Trip_Message {
            get {
                return ResourceManager.GetString("Done_Trip_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיימת את הטיול!.
        /// </summary>
        public static string Done_Trip_Title {
            get {
                return ResourceManager.GetString("Done_Trip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיום.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שגיאה.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תקלה בכניסה לחשבון גוגל.
        /// </summary>
        public static string error_in_google_login {
            get {
                return ResourceManager.GetString("error_in_google_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא ניתן להתחיל את הטיול. יש למלא את כל הפרטים..
        /// </summary>
        public static string error_in_group_creation {
            get {
                return ResourceManager.GetString("error_in_group_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תגובה.
        /// </summary>
        public static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רגע לפני סיום.
        /// </summary>
        public static string FeedbackPageTitle {
            get {
                return ResourceManager.GetString("FeedbackPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רמז אחרון.
        /// </summary>
        public static string final_hint {
            get {
                return ResourceManager.GetString("final_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כל הכבוד!
        ///סיימתם את המסלול.
        /// </summary>
        public static string FinishTrackPageTitle {
            get {
                return ResourceManager.GetString("FinishTrackPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יעד ראשון.
        /// </summary>
        public static string First_Attraction {
            get {
                return ResourceManager.GetString("First_Attraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבוצה.
        /// </summary>
        public static string group {
            get {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם קבוצה:.
        /// </summary>
        public static string group_name {
            get {
                return ResourceManager.GetString("group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחילו משחק.
        /// </summary>
        public static string GroupCreationPage_start_game {
            get {
                return ResourceManager.GetString("GroupCreationPage_start_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צרו קבוצה.
        /// </summary>
        public static string GroupCreationPageTitle {
            get {
                return ResourceManager.GetString("GroupCreationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to היי.
        /// </summary>
        public static string Hey {
            get {
                return ResourceManager.GetString("Hey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רמז.
        /// </summary>
        public static string hint {
            get {
                return ResourceManager.GetString("hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רמזים.
        /// </summary>
        public static string hints {
            get {
                return ResourceManager.GetString("hints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איך משחקים?.
        /// </summary>
        public static string how_to_play {
            get {
                return ResourceManager.GetString("how_to_play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מידע נוסף.
        /// </summary>
        public static string infoBtn {
            get {
                return ResourceManager.GetString("infoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מידע.
        /// </summary>
        public static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עכשיו בגלריות האוניברסיטה.
        /// </summary>
        public static string informationFirstPage {
            get {
                return ResourceManager.GetString("informationFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מידע.
        /// </summary>
        public static string InformationPageTitle {
            get {
                return ResourceManager.GetString("InformationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הנחיות.
        /// </summary>
        public static string InstructionsPageTitle {
            get {
                return ResourceManager.GetString("InstructionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התמונה התפרקה, עזרו לנו להחזיר את כל החתיכות למקום.
        /// </summary>
        public static string JigsawPuzzlePageTitle {
            get {
                return ResourceManager.GetString("JigsawPuzzlePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רמז אחרון.
        /// </summary>
        public static string last_hint {
            get {
                return ResourceManager.GetString("last_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרמז האחרון חושף את המיקום של האטרקצייה על המפה, האם אתה בטוח שברצונך להשתמש ברמז זה?.
        /// </summary>
        public static string Last_Hint_Alert_Message {
            get {
                return ResourceManager.GetString("Last_Hint_Alert_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרמז האחרון!.
        /// </summary>
        public static string Last_Hint_Alert_Title {
            get {
                return ResourceManager.GetString("Last_Hint_Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלת ניקוד.
        /// </summary>
        public static string leading_Table {
            get {
                return ResourceManager.GetString("leading_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלת ניקוד.
        /// </summary>
        public static string LeadingTablePageTitle {
            get {
                return ResourceManager.GetString("LeadingTablePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כניסה ללא התחברות.
        /// </summary>
        public static string login_as_anonymous {
            get {
                return ResourceManager.GetString("login_as_anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחבר עם פייסבוק.
        /// </summary>
        public static string login_with_facebook {
            get {
                return ResourceManager.GetString("login_with_facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחבר עם חשבון גוגל.
        /// </summary>
        public static string login_with_google {
            get {
                return ResourceManager.GetString("login_with_google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחברות.
        /// </summary>
        public static string LoginsPageTitle {
            get {
                return ResourceManager.GetString("LoginsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארוך(כשעה וחצי).
        /// </summary>
        public static string long_path {
            get {
                return ResourceManager.GetString("long_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מפה.
        /// </summary>
        public static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בינוני(כשעה).
        /// </summary>
        public static string medium_path {
            get {
                return ResourceManager.GetString("medium_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משימה.
        /// </summary>
        public static string mission {
            get {
                return ResourceManager.GetString("mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשימה הושלמה.
        /// </summary>
        public static string missionComplete {
            get {
                return ResourceManager.GetString("missionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ענו על השאלה.
        /// </summary>
        public static string MultipleChoiceQuestionPageTitle {
            get {
                return ResourceManager.GetString("MultipleChoiceQuestionPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רמז לנקודה הבאה.
        /// </summary>
        public static string NavigationPageTitle {
            get {
                return ResourceManager.GetString("NavigationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרמז הבא יגרור
        ///הורדה בניקוד.
        /// </summary>
        public static string next_hint_alert {
            get {
                return ResourceManager.GetString("next_hint_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא הגעת.
        /// </summary>
        public static string not_arrived {
            get {
                return ResourceManager.GetString("not_arrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשך.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אופציה 1.
        /// </summary>
        public static string Option_1 {
            get {
                return ResourceManager.GetString("Option_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אופציה 2.
        /// </summary>
        public static string Option_2 {
            get {
                return ResourceManager.GetString("Option_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to או.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to היכנסו לקמפוס לשחק.
        /// </summary>
        public static string Out_Of_Valid_Sector_Message {
            get {
                return ResourceManager.GetString("Out_Of_Valid_Sector_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אתה נמצא מחוץ לגבולות הגזרה.
        /// </summary>
        public static string Out_Of_Valid_Sector_Title {
            get {
                return ResourceManager.GetString("Out_Of_Valid_Sector_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אורך מסלול:.
        /// </summary>
        public static string path_length {
            get {
                return ResourceManager.GetString("path_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחילו לשחק.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos; שחקן.
        /// </summary>
        public static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גיל.
        /// </summary>
        public static string Players_Ages {
            get {
                return ResourceManager.GetString("Players_Ages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צפייה בסרטון.
        /// </summary>
        public static string playVideoBtn {
            get {
                return ResourceManager.GetString("playVideoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נקודות.
        /// </summary>
        public static string points {
            get {
                return ResourceManager.GetString("points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקום.
        /// </summary>
        public static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פאזל.
        /// </summary>
        public static string puzzle {
            get {
                return ResourceManager.GetString("puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שאלה אמריקאית.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השב.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אפס.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשך.
        /// </summary>
        public static string save_and_continue {
            get {
                return ResourceManager.GetString("save_and_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניקוד.
        /// </summary>
        public static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שיתוף.
        /// </summary>
        public static string share {
            get {
                return ResourceManager.GetString("share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם אתה רוצה לשתף ב .
        /// </summary>
        public static string Share_First_Part_Message {
            get {
                return ResourceManager.GetString("Share_First_Part_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to או באפליקציה אחרת?.
        /// </summary>
        public static string Share_Second_Part_Message {
            get {
                return ResourceManager.GetString("Share_Second_Part_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to היכן תרצה לשתף?.
        /// </summary>
        public static string Share_Title {
            get {
                return ResourceManager.GetString("Share_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קצר(כחצי שעה).
        /// </summary>
        public static string short_path {
            get {
                return ResourceManager.GetString("short_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחברו.
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פאזל הזזה.
        /// </summary>
        public static string sliding_puzzle {
            get {
                return ResourceManager.GetString("sliding_puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התמונה התערבבה, עזרו לנו לסדר אותה.
        /// </summary>
        public static string SlidingPuzzlePageTitle {
            get {
                return ResourceManager.GetString("SlidingPuzzlePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחל מסלול.
        /// </summary>
        public static string start_trip {
            get {
                return ResourceManager.GetString("start_trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טקסט על הפסל.
        /// </summary>
        public static string subtitlesBtn {
            get {
                return ResourceManager.GetString("subtitlesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצלחה.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צלמו תמונה.
        /// </summary>
        public static string take_picture {
            get {
                return ResourceManager.GetString("take_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צלם תמונה.
        /// </summary>
        public static string taking_picture {
            get {
                return ResourceManager.GetString("taking_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצטלמו עם הפסל.
        /// </summary>
        public static string TakingPicturePageTitle {
            get {
                return ResourceManager.GetString("TakingPicturePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שגית יותר מ.
        /// </summary>
        public static string Too_Much_Mistakes_In_AQ_Message_Part1 {
            get {
                return ResourceManager.GetString("Too_Much_Mistakes_In_AQ_Message_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פעמים. ולכן תאלץ לחכות.
        /// </summary>
        public static string Too_Much_Mistakes_In_AQ_Message_Part2 {
            get {
                return ResourceManager.GetString("Too_Much_Mistakes_In_AQ_Message_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שניות.
        /// </summary>
        public static string Too_Much_Mistakes_In_AQ_Message_Part3 {
            get {
                return ResourceManager.GetString("Too_Much_Mistakes_In_AQ_Message_Part3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עצור.
        /// </summary>
        public static string Too_Much_Mistakes_In_AQ_title {
            get {
                return ResourceManager.GetString("Too_Much_Mistakes_In_AQ_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צפה שוב.
        /// </summary>
        public static string watch_again {
            get {
                return ResourceManager.GetString("watch_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כן.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגעת ליעד.
        /// </summary>
        public static string You_have_Reached_Your_Destionation {
            get {
                return ResourceManager.GetString("You_have_Reached_Your_Destionation", resourceCulture);
            }
        }
    }
}
